### ISSUE TITLE
Implement back-end functionality for the feedback form on the home page

### ISSUE THREAD

**Issue by yemisi-o** [she-code-africa/SCA-Website#13]
This is to implement the actual form submission functionality for the feedback form on the home page (currently it is static) such that when a user fills in the form and submits, the data submitted on the form is added to the backend and listed on the admin's page.

Since Keystone already comes with a contact form, this can be utilised to be used for the feedback form i.e. the existing contact form functionality can be used to implement the back-end of the feedback form and the Enquiries page on the admin page will have all submitted responses from the form.

Error handling and data validation on the form should be ensured on both the front-end and the back-end

**Acceptance Criteria**:

- Given that I am a user when I fill in all required fields on the feedback form, I should be able to make a successful submission when I click on the Submit button
- Given that I am a user when I do not fill in all required fields on the feedback form, I should be prompted to fill in those fields and NOT be able to make a successful submission until there is data in all required fields
- Given that I am an admin user when I visit the Enquiries page on Admin I should be able to see all submitted inquiries from the feedback form

**Comment by TARIEPEACE** [comment]
ISSUE COMPLETED 11 JULY 2018

**Comment by yemisi-o** [comment]
This is not done yet
