### ISSUE TITLE
Update design for the blog pages

### ISSUE THREAD

**Issue by yemisi-o** [she-code-africa/SCA-Website#16]
The implementation of the blog home page design is yet to be completed, this is to complete the design implementation of the blog page in Nunjucks since the project for a start will be using the Nunjucks template. The design of the main blog home page has already been implemented to some extent

Design can be found here - https://www.figma.com/file/l0HWd8JRSxNVNCx5yg4ODy/She-code-Africa-(Copy)?node-id=74%3A0

Specifically, the changes still required for the front-end part of the code includes:

- [ ] Complete implementation of the design for the blog home page
- [ ] Update the default design for the individual post page to fit that of SheCodeAfrica styling
- [ ] Update the default design for individual category page

**Comment by temilolakutelu** [comment]
The blog page layout is ready
