### ISSUE TITLE
Make blog image upload functionality work

### ISSUE THREAD

**Issue by yemisi-o** [she-code-africa/SCA-Website#34]
We are looking to address 2 things here, 1 is making a blog post main/header image work appropriately, the 2nd thing is making it possible to upload an image when creating a post.

Keystone comes with Cloudinary support which is what is used for the main post image upload (not yet properly configured so doesn't work), and they also have support for Amazon. However, the first question is if we want to go ahead with Cloudinary, s3, or another option entirely. The final decision will be based on the cost for long-term use (i.e. when we have more images/traffic), any other options available, and implementation effort to make it work as we want. TBD

A major advantage of using Cloudinary may be that it also handles image optimisation and transformation for us which is useful for blog posts and performance. The following links contain more information on the file/image upload options available in Keystone

https://v4.keystonejs.com/api/field/file/
https://v4.keystonejs.com/api/field/cloudinaryimage/

This article may also have helpful information - http://christroutner.com/blog/post/uploading-images-via-the-api-part-1

Whatever option we go with, we need to ensure it works properly for the main image upload and make adjustments where necessary. Then also:

- [x] **Allow images to be added within content extended**: When an admin is creating a post, they should be able to add images in between the posts. Ideally, as an image upload but since we have plans to switch the editor to Markdown  (#41)  it may be ideal to just leave it as insertion/addition via links.

- [ ] **Option to add alt-text and description/caption to images**: When an admin uploads an image or adds an image via a link, an option should be provided for them to input an alt-text for the image and also a description of the image

**Comment by mazma1** [comment]
#### Update on task:
1. When I created a test post, I was able to upload a main image so there was nothing for me to do on that.
2. On adding an image within content extended, I don't think there is a way for image upload in between post. You can't possibly add an image upload button/link inside the editor. If you paste a link to an image, it is rendered like a normal string of text without expanding the image.

    The only option I can think is to change to a markdown editor, which allows you insert images in between texts. I've done this, but I have a problem rendering the markdown in Nunjuncks. I've tried [this package](https://www.npmjs.com/package/nunjucks-markdown) but it isn't working for me. I'm still trying to see what else can be done

**Comment by yemisi-o** [comment]
Well done @mazma1 and thanks for the update. Changing the editor to markdown is fine as there already plans to change it (See #41), let's see if we can figure out making it work with Nunjucks
